### ISSUE TITLE
Host and User commands

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur-authn-k8s-client#199]
## **Feature Overview & Customer Need**

**As a**  Conjur user 
**I would like to** use the conjur cli 
**In order to** update my password 

**As a**  Conjur user or host
**I would like to** use the conjur cli 
**In order to** rotate API Key of a user or a host (it can also be me :))

## COMMANDS

rotate-api-key   Rotate a user's or host's API key. If no user/host ID is provided the logged in resource's API Key is rotated.

change-password    Update the password of the logged-in user either the command is interactive meaning password is requested from the user or it is provided by -p /--password.

## Help

For each command and subcommand a help is needed see here:
Help for host: https://ljfz3b.axshare.com/#id=paicg6&p=conjur_help__user&g=1
Help for user: https://ljfz3b.axshare.com/#id=paicg6&p=conjur_help__user&g=1

## Quality

Make sure we have test coverage of the host commands.  Create test plan and execute accordingly.

## Process logic and Demo

Conjur use with a machine that the Python CLI already been installed and conjur init & login ran

Now the user run the following commands:

`conjur user  rotate-api-key  <user_id> `

show the result of rotate-api-key

`conjur user  change-password  -p new_pass
`
show response 

`conjur host rotate-api-key  <host_id> 
`
show the result of rotate-api-key

## User messages

All user messages regarding host and user should be reviewed again

Especially error messages 

if an argument is missing we need to return the help of the command 

## UX Guidelines

Follow guidelines here: https://github.com/cyberark/conjur-api-python3/blob/master/guidelines/python-cli-ux-guidelines.md

## **Documentation**

Please provide enhance documentation in online help and readme

## DOD

- [ ] Implement the user command & subcommands Conjur Python CLI in all 3 platforms
- [ ] Implement the host command & subcommands Conjur Python CLI in all 3 platforms
- [ ] Demo the flow described above
- [ ] Automatic integration tests written according to a test plan and passed successfully
- [ ] UT written for all classes\functions\major logic flows and passed successfully
- [ ] Security action items were taken
- [ ] Supportability was taken into account - troubleshooting section in the readme enhanced and reviewed by TW & PO
- [ ] Fill in the user messages - link to a page with all user messages for CLI saved and reviewed. 
- [ ] Fill in the logs and place here a link to the logs files - link to a page with all logs for CLI saved and reviewed. 
- [ ] Logs were reviewed by TW and PO
- [ ] Are there new Audits to this feature? If so please document them and provide here a link
- [ ] Configurations were reviewed by PO - link if something changed
- [ ] Documentation HO to TW and review docs
