### ISSUE TITLE
FIPS compliance for authn-client-k8s

### ISSUE THREAD

**Issue by hilagross** [cyberark/conjur-authn-k8s-client#91]
# FIPS compliance for authn-client-k8s

### Overview
The National Institute of Standards and Technology (NIST) issued the [FIPS 140-2](https://csrc.nist.gov/publications/detail/fips/140/2/final) Publication Series to coordinate the requirements and standards for cryptography modules that include both hardware and software components. 

The requirements are to support FIPS in all cryptography 3rd parties, preferably as one source code if possible, otherwise by configuration. 

As making Conjur product FIPS compliant, our costumer will gain a cryptographic standard to protect their unclassified, but sensitive data.

As part of the effort of making Conjur FIPS compliant, we tackled an issue regarding Golang. 
The issue is that Golang, by nature, is not FIPS compliant and they claim that they are not going to be (https://github.com/golang/go/issues/11658#issuecomment-120441723). 

There are three alternatives:
1. Use cgo to call out to an existing certified library
   - This alternative disqualified due to its complexity and consuming time and effort as we will have to replace any usage of crypto.

2. Use BoringSSL based crypto
   - Use [Google’s fork of Golang](https://github.com/golang/go/blob/dev.boringcrypto.go1.12/misc/boring/README.md) that uses dev.boringcrypto as its crypto engine. dev.boringcrypto wraps BoringSSL which is FIPS compliant.
   - disadvantage of this approach is that Google does not guarantee any “support” or responsibility on this version being FIPS compliant.
3. Use [RHEL go toolchain](https://developers.redhat.com/blog/2019/06/24/go-and-fips-140-2-on-red-hat-enterprise-linux/).
   - RHEL takes the ownership on the encryption, and bridges between the Golang encryption and OpenSSL.
   - What needs to be done is build the Golang project on subscribed RHEL machine/UBI container with the relevant go-toolset installed on it. than, we can take the compiled binary and copy it into the containers as usual.
   - A big advantage of this approach is that we are aligning with Red Hat which is one of the big players in the field of certifications, enterprise, and federal market. 
   - The pipeline should use and subscribe RHEL / UBI on-the-fly.

### Requirement

Compare all options (cgo, google toolset, RHEL) and decide on the best approach. should include also in seed-fetcher container.
Consider all 3 alternatives:
1. Use cgo to call out to an existing certified library
2. Use BoringSSL based crypto.
3. Use RHEL go toolchain.
Create a test plan and design the solution before implementing it.

**our goal:**
- Compare and decide on the best approach for Conjur, summarize it a confluence page.
- Validate with PO and Security expert 
- Run a POC of the approach
- Design a solution 
- Leverage to other Golang projects - currently out of this scope, but we should keep in mind it will have to include other projects.

**Consider:**
a. Dev vs Test vs Prod
   i. UX wise
   ii. Pipeline
   iii. RHEL subscription (PR needed?)

b. If deciding on the 3rd option (RHEL), we should compare between RHEL and UBI
   i. PoC
   ii. Understand concerns
   iii. share with security expert

**Performance**
Same SLA of performance should be kept. 

### DoD

- [x] Compare and decide on the best approach for Conjur alternatives (cgo, google toolset, RHEL), summarize it in a page.
- [x] Validate the approach with PO and Security expert
- [x] Solution design written and reviewed by PO and security expert
- [x] Test plan written and reviewed by PO & QAA
- [x] Design presented and shared
- [x] High level effort estimations and risks
- [x] PoC the approach
- [x] Understand Dev vs Test vs Prod

## Team
- **Product Manager**:  _Hila Gross_ (@hilagross)
- **Product Owner**: _Hila Gross_ (@hilagross)
- **Engineering Manager**: _Dekel Asaf_ (@Tovli)
- **Feature Lead**: _Shahar Glazner_
- **Engineers**:
    - _Oren Ben Meir_ (@orenbm )
- **Technical Writer**: _Shuli_

## SDLC Timeline

|Stage|Updates|Artifact|
|-|-|-|
|Project Initialization|![](https://img.shields.io/static/v1.svg?message=Started&color=green)||
|Kickoff|![](https://img.shields.io/static/v1.svg?message=Started&color=green)||
|Feature Proposal|![](https://img.shields.io/static/v1.svg?message=Started&color=green)||
|Functional Sign-off|![](https://img.shields.io/static/v1.svg?message=Started&color=green)||
|Technical D&D|![](https://img.shields.io/static/v1.svg?message=Started&color=green)||
|Solution Sign-off|![](https://img.shields.io/static/v1.svg?message=Started&color=green)||
|Execution|![](https://img.shields.io/static/v1.svg?message=Started&color=green)||
|Acceptance|![](https://img.shields.io/static/v1.svg?label=YYYY-MM-DD&message=Not%20Started&color=lightgrey)||

**Comment by izgeri** [comment]
Is it possible to create a separate FIPS-compliant image of golang and keep pretty much everything else the same?

For example, it appears from the [boringcrypto﻿ docs](https://github.com/golang/go/blob/dev.boringcrypto.go1.12/misc/boring/README.md#building-from-docker) that you can use the [goboring Docker image﻿](https://hub.docker.com/r/goboring/golang) in place of the standard golang Docker image with (likely) no other modifications.

Can we add a `Dockerfile.fips` to this project that uses the `goboring` base image but is otherwise identical to the `Dockerfile`, and is only built when a special command is passed to `./bin/build`? That would preserve the development experience in almost all cases, and the pipeline could build this custom image in addition to the other images and push it to DockerHub and/or our internal registry.

**Comment by Tovli** [comment]
@hilagross - I think a PR would be easier for comments

regarding the doc - is this a requirement?
"Compiling the authenticator on RHEL"
why do we must use RHEL?

**Comment by orenbm** [comment]
@shaharglazner @hilagross how do we decide that a solution is FIPS compliant. For example, in the description of the GoBoring solution you say `disadvantage of this approach is that Google does not guarantee any “support” or responsibility on this version being FIPS compliant.`. Does this mean that we can't use this solution?

**Comment by orenbm** [comment]
@izgeri when you say 
```
Can we add a Dockerfile.fips to this project that uses the goboring base image but is otherwise identical to the Dockerfile, and is only built when a special command is passed to ./bin/build? 
```

why would we have another image instead of building our main image from the goboring base image? Are there any risks here?

**Comment by izgeri** [comment]
@orenbm `goboring` is a fork of Go (see [here](https://go.googlesource.com/go/+/dev.boringcrypto/README.boringcrypto.md)).

What is the benefit to all of our customers from requiring that the binary is built using FIPS-compliant libraries for everyone? It does not add much complexity for us to build the binary using the official Golang project and distribute Docker images that include that, and separately create a binary using the goboring and distribute a Docker image which includes that for end-users interested in a FIPS-compliant version of this project.

**Comment by orenbm** [comment]
thanks @izgeri , that sounds like a good reason. It's really not hard to have 2 images, just wondered why we need the original one.

**Comment by izgeri** [comment]
@orenbm there is more work in this epic still, correct? I understood there would be additional test changes to happen - is there a separate issue for tracking that work?

**Comment by orenbm** [comment]
@izgeri you are correct. It moved to Closed by accident when I merged #97.

I added now all the relevant issues that needs to be done as part of this effort.

Thanks!
